import Footer from '@/components/footer';
import { Button } from '@/components/ui/button';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'Privacy Policy for AI Playground - Learn how we collect, use, and protect your data.',
};

export default function PrivacyPolicyPage() {
  return (
    <div className='min-h-screen bg-background'>
      <main className='mx-auto max-w-4xl px-6 py-16'>
        <div className='mb-8'>
          <Button asChild variant='outline' className='mb-6'>
            <Link href='/'>← Back to Home</Link>
          </Button>

          <h1 className='text-4xl font-bold tracking-tight'>Privacy Policy</h1>
          <p className='mt-4 text-muted-foreground'>
            Last updated:{' '}
            {new Date().toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}
          </p>
        </div>

        <div className='prose prose-slate dark:prose-invert max-w-none'>
          <p className='text-lg text-muted-foreground mb-8'>
            AI Playground (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is an open-source web
            application designed to help users test and compare AI models side-by-side. We take your
            privacy seriously and are committed to being transparent about what we store, what we
            don&apos;t store, and how your data is handled.
          </p>

          <section className='mb-10'>
            <h2 className='text-2xl font-semibold mb-4'>1. Information We Collect</h2>

            <h3 className='text-xl font-medium mb-3 mt-6'>1.1 User Credentials</h3>
            <p className='text-muted-foreground mb-4'>
              We only store the minimum amount of information required to provide user accounts.
              This includes:
            </p>
            <ul className='list-disc pl-6 space-y-2 text-muted-foreground mb-4'>
              <li>Your email address</li>
              <li>Your hashed authentication credentials</li>
            </ul>
            <p className='text-muted-foreground'>These are securely stored in our database.</p>
          </section>

          <section className='mb-10'>
            <h2 className='text-2xl font-semibold mb-4'>
              2. Information We Do Not Collect or Store
            </h2>

            <h3 className='text-xl font-medium mb-3 mt-6'>2.1 AI Prompts & Conversations</h3>
            <p className='text-muted-foreground mb-4'>
              We <strong>do not store</strong>:
            </p>
            <ul className='list-disc pl-6 space-y-2 text-muted-foreground mb-4'>
              <li>Your prompts</li>
              <li>Your messages</li>
              <li>Your chat history</li>
              <li>Any responses generated by AI models</li>
            </ul>
            <p className='text-muted-foreground mb-6'>
              All prompt data remains ephemeral and never touches our database.
            </p>

            <h3 className='text-xl font-medium mb-3 mt-6'>2.2 API Keys</h3>
            <p className='text-muted-foreground mb-4'>
              We <strong>do not store</strong> any AI provider API keys you use:
            </p>
            <ul className='list-disc pl-6 space-y-2 text-muted-foreground mb-4'>
              <li>OpenAI</li>
              <li>Anthropic</li>
              <li>xAI</li>
              <li>Google</li>
              <li>Or any other future providers</li>
            </ul>
            <p className='text-muted-foreground'>
              Your API keys remain client-side or securely stored in your own session (depending on
              your configuration). They are never saved in our database.
            </p>
          </section>

          <section className='mb-10'>
            <h2 className='text-2xl font-semibold mb-4'>3. How Your Data Flows</h2>
            <p className='text-muted-foreground mb-4'>When you use AI Playground:</p>
            <ol className='list-decimal pl-6 space-y-2 text-muted-foreground mb-4'>
              <li>You write a prompt in the interface.</li>
              <li>
                The prompt is <strong>directly sent to the selected AI provider</strong> using{' '}
                <strong>your own API key</strong>.
              </li>
              <li>The provider processes the request and returns the response to you.</li>
            </ol>
            <p className='text-muted-foreground'>
              At no point is the prompt or response stored by us.
            </p>
          </section>

          <section className='mb-10'>
            <h2 className='text-2xl font-semibold mb-4'>4. Cookies & Session Storage</h2>
            <p className='text-muted-foreground mb-4'>
              We may use cookies or local/session storage <strong>only</strong> for:
            </p>
            <ul className='list-disc pl-6 space-y-2 text-muted-foreground mb-4'>
              <li>Maintaining authentication sessions</li>
              <li>Basic app functionality</li>
            </ul>
            <p className='text-muted-foreground'>
              We do <strong>not</strong> use cookies for tracking, profiling, advertising, or
              analytics.
            </p>
          </section>

          <section className='mb-10'>
            <h2 className='text-2xl font-semibold mb-4'>5. Security</h2>
            <p className='text-muted-foreground'>
              We use industry-standard security practices to protect user credentials and maintain a
              secure environment. However, no online service is 100% secure, and we encourage users
              to protect their API keys and use reputable providers.
            </p>
          </section>

          <section className='mb-10'>
            <h2 className='text-2xl font-semibold mb-4'>6. Open-Source Transparency</h2>
            <p className='text-muted-foreground'>
              AI Playground is an open-source project, and the codebase is publicly available. Users
              are welcome to inspect, verify, and contribute to the project.
            </p>
          </section>

          <section className='mb-10'>
            <h2 className='text-2xl font-semibold mb-4'>7. Changes to This Policy</h2>
            <p className='text-muted-foreground'>
              We may update this Privacy Policy from time to time. We will notify users of any
              material changes.
            </p>
          </section>

          <section className='mb-10'>
            <h2 className='text-2xl font-semibold mb-4'>8. Contact</h2>
            <p className='text-muted-foreground'>
              If you have any questions about this Privacy Policy, feel free to contact us at{' '}
              <a href='mailto:privacy@ai-playground.dev' className='text-primary underline'>
                privacy@ai-playground.dev
              </a>
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
